name: RestAssured-API framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    schedule:
    -cron: 00 17:37 * * *

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Execute Tests
      run: mvn clean test -Dsuite=suite -X
   - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
      Name: Logs
      path: logs/
     
